# Generated by Django 6.0.7 on 2026-07-24 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='remarks',
        ),
    ]
